### ISSUE TITLE
Issue with SQLITE upsert method

### ISSUE THREAD

**Issue by Robotv2** [GroupeZ-dev/Sarah#9]
Stacktrace with debug: https://pastebin.com/cU0FPDgV
Version used: develop-SNAPSHOT from jitpack

**Comment by Traqueur-dev** [comment]
tu dois spécifier dans ta requête quelle est la clé primaire avec la methode primary() pour gérer ensuite la clause conflict.

**Comment by Robotv2** [comment]
Super ça fonctionne, merci beaucoup

**Comment by Robotv2** [comment]
Super ça fonctionne, merci beaucoup
